// Auto-generated from Word doc. Edit text directly here if you spot a typo.
// Source docx workbook used a "Match the Idiom" exercise (Part A) and a
// phrasal-verb fill-in-the-blank exercise (Part B). Part A was converted to
// multipleChoice (each idiom -> pick its meaning) since ReadOnline.jsx's
// WorkbookTab requires multipleChoice unconditionally and has no matching-
// exercise type. Part B's two-blank cloze items (e.g. "check ___ it ___ out")
// were reworded to single-blank sentences since the component only splits on
// one "______" per question.
const bookContent = {
  "slug": "et-06-anything-but-work",
  "title": "Anything But Work",
  "series": "Everyday Together",
  "level": "A2",
  "audioSrc": "/audio/et-06-ch1.mp3",
  "story": [
      "Takumi yawned. He glanced at his watch and answered the door.",
      "Daichi stood outside. He looked exhausted. There were dark circles under his eyes. \"Morning, Takumi. Can I come in?\" he asked.",
      "\"It's six o'clock in the morning,\" Takumi said, yawning again. \"What are you doing here?\"",
      "\"I've been up all night,\" Daichi said, handing Takumi a bag from the convenience store. \"The wi-fi in my building is down. I talked to the internet company, and it will take three days to fix,\" he said. \"I have a big project due in two days, and I have to get the demo for our group, 'Out of Batteries', finished. Can I use your wi-fi?\"",
      "\"The demo?\" Takumi said, crossing his arms. \"You were supposed to have that finished last week,\" he said. \"Quiet Signal Records wants it by tomorrow.\"",
      "\"Sorry about that,\" said Daichi, bowing. \"I've been really busy with the project.\"",
      "Takumi shook his head. \"Come in,\" he said and stood aside. \"What's in the bag?\"",
      "\"Just a little thanks,\" Daichi said. \"I know you like cream puffs. They had a cookie version in the store.\"",
      "\"I'll get you the password,\" said Takumi. He took the bag and led Daichi to the living room.",
      "\"Great. I'll get set up and finish this project,\" said Daichi. He put his computer on the table and opened it up.",
      "Takumi handed him a piece of paper with the wi-fi password and a cup of coffee. \"When did the wi-fi go down?\" he asked Daichi.",
      "\"Last night,\" said Daichi. He took a sip of the coffee and smiled.",
      "\"Did you go to an internet cafe to work?\" Takumi asked.",
      "Daichi shook his head. \"No. My other project is very important, and I have to upload some very important files. I couldn't trust their security,\" he said. \"I did as much work as I could offline.\"",
      "\"Okay,\" Takumi said and stood up. \"Make yourself at home. I have to get ready for work.\"",
      "\"When do you leave?\" Daichi asked.",
      "\"I usually leave at eight, so I get up at seven,\" said Takumi.",
      "Daichi put his hands together in apology. \"Sorry. I didn't mean to wake you up so early.\"",
      "\"It's okay. I have more time to practice my keigo,\" Takumi said.",
      "\"Is that still giving you trouble?\" Daichi asked.",
      "\"Oh yeah,\" Takumi said, shaking his head. \"I called my boss, 'Dude,' last week. He didn't mind, but the rest of the office laughed.\"",
      "Daichi laughed. \"That's why I love freelancing,\" he said.",
      "\"I'll let you work,\" Takumi said and went into the bathroom to get ready.",
      "When he came out twenty minutes later, Daichi was dusting his shelves with a cloth.",
      "\"What are you doing?\" asked Takumi.",
      "\"Your books were out of order,\" said Daichi. \"And then I noticed that your shelves were very dusty.\" He shook his head. \"I couldn't work in a dirty room.\"",
      "Takumi took the cloth from Daichi. \"Your room is even dirtier,\" he said. \"You never clean it.\"",
      "\"I had to last night,\" said Daichi. He bit his lip. \"When the wi-fi went down, I couldn't sleep. I needed to clean.\"",
      "\"Later,\" said Takumi. \"Did you finish uploading the files?\"",
      "\"Yes, but I have to wait,\" said Daichi. \"The manager isn't in yet.\" He sat down on the floor.",
      "\"Why don't you work on the demo?\" asked Takumi.",
      "\"I will,\" said Daichi. \"Once the manager says my file is okay, I'll get started on the music demo.\" He smiled. \"It should be ready soon.\"",
      "Takumi shook his head.",
      "\"I'm hungry,\" said Daichi. \"Do you want to go get some breakfast?\"",
      "\"I usually just have a banana for breakfast,\" said Takumi. \"I have some cereal if you want.\"",
      "Daichi yawned. \"Maybe later. Is it all right if I take a nap?\" he asked.",
      "\"That's right, you've been up all night,\" Takumi said. He looked at his watch and frowned. \"I have to leave in an hour.\"",
      "\"Okay,\" Daichi said. \"I'll go find an internet cafe.\"",
      "Takumi held out his hands. \"No. It's okay. You can stay here today,\" he said. \"I'll leave you my extra key. When you go outside, please lock the door.\"",
      "\"Thanks, buddy,\" Daichi said. \"I promise I won't make a mess.\"",
      "***SCENE_BREAK***",
      "\"So Daichi just turned up at your door this morning?\" asked Yui. She had a bag from the convenience store with three onigiri. They were walking to Takumi's apartment. Yui lived near him.",
      "\"Yes,\" said Takumi. \"He needed a place to work on our demo and finish a project. I let him use my wi-fi.\"",
      "\"You left Dai-chan all alone in your apartment,\" said Yui, smiling. \"Are you sure it was a good idea?\"",
      "\"Why?\" asked Takumi. \"He said he would finish the demo by this afternoon.\"",
      "Yui shook her head. \"I bet you these three onigiri that he hasn't,\" she said.",
      "\"You're on,\" Takumi said. He opened the door. The room was dark, and there was loud snoring from the front room.",
      "\"Daichi?\" Takumi said. He and Yui went into the living room. Daichi was lying on the couch. His computer was dark.",
      "Takumi touched Daichi's shoulder. \"Hey. Are you okay?\"",
      "Daichi snorted and sat up. \"Takumi. You're home. Sorry. I fell asleep not long after you left,\" he said. \"What time is it?\"",
      "\"Seven in the evening,\" said Takumi. \"I had some overtime. Are you hungry?\"",
      "\"Starving. Just let me check my email,\" Daichi said. He turned on his computer.",
      "\"Still think he worked on the demo?\" whispered Yui.",
      "Takumi bit his lip.",
      "\"Great. My boss loved the project,\" Daichi said. \"I can get started on the demo right after dinner.\" He looked at Takumi. \"Where do you want to go? My treat.\"",
      "\"When will you start on the demo?\" asked Takumi.",
      "\"The minute we finish dinner,\" said Daichi. \"I can't work on an empty stomach.\"",
      "\"I like salmon and kombu onigiri the best,\" said Yui, smiling.",
      "***SCENE_BREAK***",
      "\"Are you sure you can't stay, Yui?\" Daichi asked, waving a pizza.",
      "\"Sorry, Dai-chan. I've got school in the morning,\" Yui said. \"Besides, I want to watch that drama on U-Flicks. Tonight's the last night.\"",
      "Yui waved goodbye at Takumi's door. Before she left, she grabbed his arm and squeezed. \"Good luck with Dai-chan.\"",
      "\"Thanks. I'll need it,\" Takumi said.",
      "Yui smiled. \"You can get me the onigiri tomorrow.\"",
      "Takumi closed the door and went back into the living room. Daichi was putting on some earphones. \"Oh, are you going to work on the demo?\"",
      "\"No. When Yui mentioned the video, I wanted to check it out,\" Daichi said. \"I'll get started on the demo after this.\"",
      "\"How much work do you have left on it, Daichi?\" Takumi asked.",
      "\"Maybe two or three hours,\" said Daichi. \"Everything is recorded. I just have to put it together.\"",
      "Takumi nodded. \"I'm going to take a shower. Do you want one?\"",
      "\"Yes. You don't mind?\" Daichi asked.",
      "\"No, it's okay,\" Takumi said.",
      "\"Great. I'll go after you,\" said Daichi. He sat back and started watching a TV show.",
      "***SCENE_BREAK***",
      "Daichi sat down on the couch and dried his hair. \"I'll take a look at the demo now,\" he said.",
      "Takumi smiled and looked at his watch. \"Do you need me for this? I have a meeting early tomorrow,\" he said.",
      "\"No, it's okay,\" said Daichi. \"I have a recording of our guitar work and Akira's drumming. I got lots of sleep today, and I do my best work really late, anyway,\" he said. \"I'll use my headphones.\"",
      "Takumi smiled and went into his bedroom.",
      "***SCENE_BREAK***",
      "A loud noise woke Takumi up. \"What the heck?\" He looked at his clock. It said four in the morning.",
      "There was another loud noise coming from the living room. Takumi jumped out of bed and opened his bedroom door.",
      "\"What's going on here?\" Takumi asked loudly.",
      "Daichi put down his controller. \"Sorry, buddy,\" he said. \"I got too involved in the game.\"",
      "\"Game!\" Takumi said angrily. \"What about the demo?\"",
      "Daichi shook his head. \"No, I didn't like my voice, so I erased it,\" he said. \"I'll rerecord it tomorrow at my place. It's soundproof.\"",
      "\"Why do you have a soundproof room?\" Takumi asked.",
      "\"I had a YouTube channel where I uploaded games,\" Daichi said. \"I don't use it much anymore, but I got five hundred thousand views. However, I was very noisy, and the neighbors complained. So, I made a soundproof room.\"",
      "Takumi walked over to Daichi and closed his computer. \"What's this all about?\" he asked. \"Quiet Signal Records is giving us a chance. They are small, but this could be our break.\"",
      "\"I know, but...\" Daichi didn't finish his sentence.",
      "\"What is it?\" Takumi asked.",
      "Daichi looked away. \"My voice was terrible,\" he said. \"Every time I listened to the recording, it sounded worse,\" he said. \"I couldn't give them that.\"",
      "\"So, you waste time playing video games?\" said Takumi.",
      "\"I'm good at video games,\" said Daichi. \"Singing's difficult.\"",
      "\"It's not just me and you,\" Takumi said. \"Akira is counting on this. He wants to quit his teaching job.\"",
      "Daichi bit his lip. \"I know. I want to, but I can't,\" Daichi said. \"Something always distracts me.\"",
      "Takumi shook his head. \"Come on. We're going back to your place,\" he said.",
      "\"Why?\" asked Daichi.",
      "\"It's soundproof, right?\" Takumi said.",
      "Daichi nodded.",
      "\"We're going to finish recording this demo tonight, even if it kills you,\" said Takumi.",
      "***SCENE_BREAK***",
      "\"There's the convenience store,\" said Daichi. \"Let's get a snack.\"",
      "\"No, you don't need a snack,\" said Takumi. \"Come on. Your apartment is only a few minutes away.\"",
      "Daichi kicked a rock. \"I work better with food,\" he said.",
      "\"I'll get you something when we finish,\" said Takumi.",
      "Daichi was silent the rest of the way to his building. At the elevator, he pushed the button for Kaoru's floor.",
      "\"What are you doing?\" Takumi asked.",
      "\"Kaoru might be up,\" said Daichi. \"She always has the best coffee in the morning.\"",
      "\"No. Let her sleep,\" said Takumi and pushed the button for Daichi's floor. He followed Daichi to his apartment.",
      "\"Wow! This is really clean,\" said Takumi.",
      "\"I know,\" said Daichi. \"I had three bags of garbage to take out,\" he said.",
      "\"Where's your soundproof room?\" asked Takumi.",
      "Daichi pointed to a small room in the back. Inside, there was a larger computer and a guitar on a rack.",
      "\"This is great,\" Takumi said. \"You made your YouTube channel here?\"",
      "Daichi nodded.",
      "\"I'll have to check it out,\" said Takumi. \"What game was it?\"",
      "\"An old horror game. It wasn't very good. You wouldn't be interested,\" said Daichi.",
      "\"No, I want to see it after,\" said Takumi, picking up the guitar. \"I'll play while you record your voice.\"",
      "\"Yes, that's great,\" said Daichi softly. \"Do you need a drink before we start? I don't have any coffee left. I'll go to the store and get some. There's a twenty-four-hour supermarket near here.\" He stood up.",
      "Takumi sighed. \"What's wrong, Daichi?\" Takumi asked. \"You don't want to record this demo, do you?\"",
      "\"I do!\" Daichi said strongly.",
      "\"Then what is it? Why are you acting so strangely?\" Takumi asked.",
      "Daichi sat down on his computer chair. \"I love making music. I want to make the demo, but what if the music people hate it?\"",
      "\"Then we try again,\" said Takumi. \"If they say no, it isn't the end of the world. I'm sure you made many mistakes when playing your games.\"",
      "Daichi bit his lip. \"Yeah. Many mistakes,\" he said softly.",
      "\"What happened?\" Takumi asked.",
      "Daichi was silent. He took a deep breath and started. \"Gaming was easy. My channel was growing, and I was adding new games all the time,\" he said. He smiled. \"I even stopped sleeping. Yui was worried about me and got Kaoru to make sure I slept. We went to the same high school.\"",
      "\"Ka-chan?\" Takumi said.",
      "Daichi smiled. \"Yeah. Yui started calling her Ka-chan then. It was fine, but then I got too big and too successful,\" he said. \"I made a mistake, and the negative comments started coming in.\"",
      "\"What kind?\" asked Takumi.",
      "\"Stories that I was using Chappy to play the games,\" said Daichi. \"There were others. They were worse. They weren't true, but then the comments got scary.\"",
      "\"How scary?\" asked Takumi.",
      "\"I almost went to the police,\" said Daichi, looking away.",
      "Takumi waited for Daichi to continue.",
      "\"I stopped playing games, shut down my channel and stayed in my apartment for a year,\" said Daichi.",
      "\"A year?\" Takumi said, surprised.",
      "Daichi smiled. \"Kaoru and Yui would come over sometimes. One day, they pulled me out to join an English circle,\" he said.",
      "\"That's where we met,\" said Takumi. \"You were very quiet the first few times.\"",
      "Daichi nodded. \"I wasn't sure I could speak English, but your conversation was pretty easy,\" he said. \"And your Japanese is much better, minus the keigo.\"",
      "\"I'm trying,\" said Takumi.",
      "\"I know,\" said Daichi. \"I'm not worried about singing for a small audience. That's fun. But what if I make a mistake and Quiet Signal Records hate me?\" he said.",
      "Takumi took a deep breath. \"I see,\" he said, picking up the mic. \"Your songs are great. I know them well, so I'll sing. You're okay with the guitar. Make sure you get a good recording.\"",
      "\"But I'm a better singer,\" said Daichi.",
      "\"Yes, you are,\" said Takumi. \"But I have a thicker skin. For me, mistakes are okay. I don't mind it when people criticize me. I can improve. But if they are too strong, I ignore them.\" He smiled.",
      "Daichi nodded.",
      "\"Besides, I'm better looking. I always thought I would make a much better leader,\" Takumi said, smiling.",
      "Daichi grabbed the mic. \"I wrote this song,\" he said.",
      "\"Yes, and it needs a handsome boy to sing it,\" said Takumi.",
      "\"Those are fighting words,\" Daichi said.",
      "\"Are you going to sing?\" Takumi asked.",
      "\"Yes, but not with you here,\" Daichi said. \"Go downstairs to Kaoru's place and get me some coffee. She has the best blend. I'll finish the song, and we'll check it out when you come back.\"",
      "***SCENE_BREAK***",
      "Takumi knocked on the door to Kaoru's place. He heard a shuffling behind it, and the door opened.",
      "\"It's six o'clock in the morning,\" said Kaoru. \"Why are you here so early?\"",
      "\"Goodnight Kitty slippers? Where are the pajamas?\" Takumi asked, smiling.",
      "\"I will punch you,\" said Kaoru. \"Why are you here?\"",
      "\"Daichi is recording our demo,\" said Takumi. \"He wanted some coffee.\"",
      "\"I see. Come in,\" said Kaoru. \"Just wait in the entrance. I'll bring you the coffee.\" She went back to the kitchen.",
      "\"Is your wi-fi still down?\" Takumi asked.",
      "\"What do you mean?\" asked Kaoru from the kitchen.",
      "\"Daichi said the wi-fi was down. He came to my place yesterday to work on his project,\" said Takumi.",
      "\"Oh. That was repaired yesterday afternoon,\" said Kaoru.",
      "\"Why was it down?\" asked Takumi.",
      "Kaoru brought Takumi two mugs of coffee and set them on the table. \"Daichi didn't tell you?\"",
      "Takumi shook his head.",
      "\"I don't know how he did it, but Daichi knocked out the wi-fi for the whole building,\" said Kaoru. \"He said it was an accident.\"",
      "\"Really?\" said Takumi. \"Maybe he was streaming a game again, and something happened.\"",
      "Kaoru stepped back. \"He told you about that?\"",
      "Takumi nodded.",
      "\"Wow,\" Kaoru said, tucking her hair behind her ear.",
      "\"Daichi said he got some negative reviews,\" said Takumi.",
      "\"Yes. They were... very negative,\" Kaoru said.",
      "\"Really? He didn't tell me they were that bad,\" Takumi said.",
      "\"He didn't?\" Kaoru asked.",
      "Takumi shook his head.",
      "Kaoru crossed her arms. \"They were personal.\"",
      "\"That's okay,\" said Takumi. \"I don't want to know all the details. Daichi will tell me when he's ready.\" He picked up the coffee mugs.",
      "\"I'm glad you are his friend, Takumi,\" Kaoru said.",
      "\"Me too,\" Takumi said. \"I'll bring the mugs back later.\"",
      "\"Don't worry about it,\" Kaoru said. \"I got them at the Hundred Yen Store. Daichi already has twenty of them.\"",
      "***SCENE_BREAK***",
      "Daichi's apartment was quiet when Takumi went inside. He felt his stomach fall. Is he cleaning again?",
      "Daichi opened the door to his studio. \"I'm finished. Where's my coffee?\"",
      "Takumi handed him the mug. \"I just got back,\" he said, taking a sip. \"Do you want me to stay here until you send it?\" he asked.",
      "\"No, I should be okay,\" Daichi said. \"But if you could listen to the recording before you leave, that would be great.\"",
      "\"The wi-fi is working?\" Takumi asked.",
      "\"Yeah. It looks like they fixed it last night,\" said Daichi.",
      "\"That's what Kaoru said,\" said Takumi, smiling.",
      "Daichi swallowed his coffee quickly. \"Did she say anything else?\"",
      "\"She said you knocked it out,\" said Takumi.",
      "Daichi looked at his door. \"It was an accident. I swear,\" he said. \"I was trying to make it go faster.\"",
      "\"I believe you,\" said Takumi. \"Play the song. I have to go to work.\" He followed Daichi into the studio.",
      "Daichi put on the music. Takumi's guitar and Akira's drums for 'Lost in the Night' filled the room. \"This part is good,\" said Daichi.",
      "\"Be quiet,\" said Takumi. He took another sip of his coffee.",
      "Daichi's voice started slowly. He sang about meeting someone on a train platform late at night, but not seeing their face.",
      "\"I always wondered where you got the idea for this song,\" Takumi said.",
      "\"Quiet. We're getting to the good part,\" said Daichi.",
      "The song finished with Daichi watching the person disappear from the platform.",
      "\"It's really good. Much better than the live version,\" said Takumi. \"A little sad for a demo.\"",
      "\"I know. I have the pop song you sang as well,\" said Daichi. \"I'll include it on the demo.\"",
      "\"Great,\" said Takumi. \"Quiet Signal Records will love it,\" he said.",
      "\"I hope so,\" said Daichi.",
      "Takumi drank the rest of his coffee. \"I'll stop by after work to check on you,\" he said.",
      "\"Don't worry. It's ready. I'll send the demo before lunch,\" said Daichi.",
      "\"I know. I trust you,\" said Takumi. \"Then we can celebrate with some sushi. I'll call Yui and Kaoru. I need to get Yui some onigiri.\"",
      "\"Sounds great,\" said Daichi.",
      "Takumi put his coffee cup down and held out a closed fist. Daichi met it.",
      "\"Don't forget to bring back the coffee cups,\" said Takumi.",
      "Daichi looked at his cupboard. \"I do have a lot,\" he said.",
      "\"See you tonight,\" said Takumi.",
      "\"Takumi,\" Daichi started to say and stopped. He bit his lip.",
      "\"Don't worry about it, buddy. You can tell me when you're ready,\" Takumi said. \"Until then, I'm still the better choice to be the leader,\" he said, smiling.",
      "Daichi shook his head. \"Over my dead body.\"",
      "Takumi gave him another fist bump and left Daichi's apartment.",
      "Daichi finished his coffee and went back to his computer. He opened up the demo file and stared at the screen. \"Okay,\" he said. He took a deep breath and hit send."
  ],
  "vocabulary": [
      { "word": "dark circles", "translation": "\u76ee\u306e\u4e0b\u306e\u30af\u30de", "partOfSpeech": "noun phrase", "example": "He looked exhausted. There were dark circles under his eyes." },
      { "word": "offline", "translation": "\u30aa\u30d5\u30e9\u30a4\u30f3\uff08\u3067\uff09", "partOfSpeech": "adjective/adverb", "example": "I did as much work as I could offline." },
      { "word": "freelancing", "translation": "\u30d5\u30ea\u30fc\u30e9\u30f3\u30b9\u3067\u50cd\u304f\u3053\u3068", "partOfSpeech": "verb (-ing form)", "example": "That's why I love freelancing." },
      { "word": "soundproof", "translation": "\u9632\u97f3\u306e", "partOfSpeech": "adjective", "example": "I'll rerecord it tomorrow at my place. It's soundproof." },
      { "word": "blend", "translation": "\u30d6\u30ec\u30f3\u30c9\uff08\u30b3\u30fc\u30d2\u30fc\u306e\u7a2e\u985e\uff09", "partOfSpeech": "noun", "example": "She has the best blend." },
      { "word": "rejection", "translation": "\u4e0d\u63a1\u7528\u30fb\u62d2\u5426", "partOfSpeech": "noun", "example": "One rejection isn't the end of the world." },
      { "word": "criticize", "translation": "\u6279\u5224\u3059\u308b \u203b\u30af\u30ec\u30fc\u30e0\u306f\u82f1\u8a9e\u3067\u300cclaim\uff08\u4e3b\u5f35\u3059\u308b\uff09\u300d\u306e\u610f\u5473", "partOfSpeech": "verb", "example": "I don't mind it when people criticize me." },
      { "word": "controller", "translation": "\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u30fc", "partOfSpeech": "noun", "example": "Daichi put down his controller." }
  ],
  "idioms": [
      { "phrase": "make yourself at home", "meaning": "relax and act as if you are in your own home", "translation": "\u304f\u3064\u308d\u3044\u3067\u304f\u3060\u3055\u3044", "example": "Make yourself at home. I have to get ready for work." },
      { "phrase": "you're on", "meaning": "I accept your bet", "translation": "\u4e57\u3063\u305f\uff01\uff08\u8ce2\u3051\u306b\u540c\u610f\u3059\u308b\uff09", "example": "I bet you these three onigiri that he hasn't. \u2014 You're on." },
      { "phrase": "my treat", "meaning": "I will pay for this", "translation": "\u79c1\u306e\u304a\u3054\u308a\u3067\u3059", "example": "Where do you want to go? My treat." },
      { "phrase": "thicker skin", "meaning": "the ability to receive criticism without feeling upset", "translation": "\u6279\u5224\u306b\u5f37\u3044\u30fb\u6253\u305f\u308c\u5f37\u3044", "example": "I have a thicker skin. For me, mistakes are okay." },
      { "phrase": "not the end of the world", "meaning": "not as bad as it seems; things will be okay", "translation": "\u4e16\u754c\u306e\u7d42\u308f\u308a\u3067\u306f\u306a\u3044\uff08\u5927\u3057\u305f\u3053\u3068\u3067\u306f\u306a\u3044\uff09", "example": "One rejection isn't the end of the world." },
      { "phrase": "coming in", "meaning": "arriving; being received (used for messages or comments online)", "translation": "\u5c4a\u3044\u3066\u304f\u308b\u30fb\u5165\u3063\u3066\u304f\u308b", "example": "The negative comments started coming in." },
      { "phrase": "get started on", "meaning": "to begin working on something", "translation": "\u301c\u306b\u53d6\u308a\u304b\u304b\u308b", "example": "I can get started on the demo right after dinner." },
      { "phrase": "check it out", "meaning": "to look at or listen to something (informal)", "translation": "\u30c1\u30a7\u30c3\u30af\u3059\u308b\u30fb\u898b\u3066\u307f\u308b", "example": "I'll have to check it out." },
      { "phrase": "turn up", "meaning": "to arrive, often without planning (informal)", "translation": "\u3072\u3087\u3063\u3053\u308a\u73fe\u308c\u308b", "example": "So Daichi just turned up at your door this morning?" },
      { "phrase": "pull someone out", "meaning": "to help someone leave a difficult situation", "translation": "\uff08\u56f0\u96e3\u306a\u72b6\u6cc1\u304b\u3089\uff09\u5f15\u304d\u51fa\u3059", "example": "One day, they pulled me out to join an English circle." },
      { "phrase": "over my dead body", "meaning": "I will never allow this to happen (very strong refusal, often used humorously)", "translation": "\u7d76\u5bfe\u306b\u30c0\u30e1\u3060\uff08\u5f37\u3044\u62d2\u5426\u3002\u30e6\u30fc\u30e2\u30a2\u3067\u4f7f\u3046\u3053\u3068\u3082\u591a\u3044\uff09", "example": "I'm still the better choice to be the leader. \u2014 Over my dead body." }
  ],
  "workbook": {
      "wordBank": [
          "dark circles",
          "offline",
          "freelancing",
          "soundproof",
          "blend",
          "rejection",
          "criticize",
          "controller",
          "coming in",
          "get started on",
          "check out",
          "pulled out",
          "turned up"
      ],
      "fillInBlank": [
          "Daichi had ______ under his eyes because he had been up all night.",
          "Daichi did as much work as he could ______ before uploading the files.",
          "Daichi loves ______ because he can work whenever he wants.",
          "Daichi's studio is ______, so his neighbors can't hear him sing.",
          "Kaoru always has the best coffee ______ in the morning.",
          "Takumi told Daichi that one ______ isn't the end of the world.",
          "Takumi said he doesn't mind when people ______ him.",
          "Daichi put down his ______ when Takumi walked in.",
          "Daichi's YouTube channel was growing fast. Then the negative comments started ______.",
          "Takumi said, \"I have to leave soon, but let's ______ the demo first.\"",
          "\"There's a great new song on the radio,\" said Yui. \"You should ______ that song.\"",
          "Kaoru and Yui ______ Daichi from his apartment after he stayed inside for a year.",
          "Nobody invited Daichi. He just ______ at Takumi's door at six in the morning.",
          "\"You should ______ Daichi's old YouTube channel,\" said Takumi. \"It was very popular.\""
      ],
      "fillInBlankAnswers": [
          "dark circles",
          "offline",
          "freelancing",
          "soundproof",
          "blend",
          "rejection",
          "criticize",
          "controller",
          "coming in",
          "get started on",
          "check out",
          "pulled out",
          "turned up",
          "check out"
      ],
      "multipleChoice": [
          {
              "question": "What does \"make yourself at home\" mean?",
              "options": [
                  "Relax and act as if you are in your own home.",
                  "I will pay for this.",
                  "I accept your bet."
              ],
              "answer": 0,
              "explanation": "It's used to tell a guest to relax, not to talk about paying or betting."
          },
          {
              "question": "What does \"you're on\" mean?",
              "options": [
                  "I will pay for this.",
                  "I accept your bet.",
                  "Not as bad as it seems; things will be okay."
              ],
              "answer": 1,
              "explanation": "\"You're on\" is used to accept a bet or challenge."
          },
          {
              "question": "What does \"my treat\" mean?",
              "options": [
                  "I will pay for this.",
                  "The ability to receive criticism without feeling upset.",
                  "I will never allow this (strong refusal)."
              ],
              "answer": 0,
              "explanation": "\"My treat\" means the speaker is paying for something."
          },
          {
              "question": "What does \"not the end of the world\" mean?",
              "options": [
                  "I accept your bet.",
                  "Not as bad as it seems; things will be okay.",
                  "Relax and act as if you are in your own home."
              ],
              "answer": 1,
              "explanation": "It's used to reassure someone that a bad result isn't a disaster."
          },
          {
              "question": "What does \"over my dead body\" mean?",
              "options": [
                  "I will never allow this to happen (a strong, often humorous refusal).",
                  "I will pay for this.",
                  "The ability to receive criticism without feeling upset."
              ],
              "answer": 0,
              "explanation": "It's a strong (often joking) way of refusing to let something happen."
          },
          {
              "question": "What does \"thicker skin\" mean?",
              "options": [
                  "Not as bad as it seems; things will be okay.",
                  "The ability to receive criticism without feeling upset.",
                  "I accept your bet."
              ],
              "answer": 1,
              "explanation": "Having a \"thicker skin\" means criticism doesn't bother you much."
          }
      ],
      "writeYourOwn": [
          {
              "phrase": "thicker skin",
              "meaning": "The ability to receive criticism without feeling upset. Example: \"I have a thicker skin. For me, mistakes are okay.\"",
              "prompt": "Write a sentence using \"thicker skin.\" Think about a time you had to accept criticism calmly."
          },
          {
              "phrase": "not the end of the world",
              "meaning": "Not as bad as it seems; things will be okay. Example: \"One rejection isn't the end of the world.\"",
              "prompt": "Write a sentence using \"not the end of the world.\" Think about a small mistake or setback you got over."
          },
          {
              "phrase": "over my dead body",
              "meaning": "A strong, often humorous refusal. Example: \"I'm still the better choice to be the leader.\" \u2014 \"Over my dead body.\"",
              "prompt": "Write a sentence using \"over my dead body.\" Think of something you would strongly (and playfully) refuse to allow."
          }
      ]
  }
};

export default bookContent;
