// Auto-generated from Word doc. Edit text directly here if you spot a typo.
// A2+ edition of Book 6 — same plot and characters as et-06, with elevated
// idiom/register vocabulary. No audio recorded yet; add audioSrc when available.
//
// Note: the source docx's workbook answer key still said "coming in" for Q7
// (carried over from the Book 6 base edition), but this A2+ story text uses
// the elevated idiom "pouring in" instead. The fill-in-blank below targets
// "pouring in" to match what's actually in this edition's story — flag if
// you'd rather keep "coming in" for consistency with the printed worksheet.
const bookContent = {
  "slug": "et-06-2-anything-but-work",
  "title": "Anything But Work (A2+ Edition)",
  "series": "Everyday Together",
  "level": "A2+",
  // audioSrc: '/audio/et-06-2-ch1.mp3', // TODO: add when recorded
  "story": [
      "The pounding on the door continued, shaking the flimsy walls. \"Hold your horses, I'm coming!\" Takumi yawned, yanking open the door.",
      "Daichi stood outside, with dark circles under his eyes. \"Morning, Takumi. Can I come in?\" he asked.",
      "\"It's six o'clock in the morning.\" Takumi yawned again. \"What are you doing here?\"",
      "\"I've been up all night.\" Daichi handed Takumi a bag from the convenience store. \"The wi-fi in my building is down. I talked to the internet company. It will take them about three days to fix it,\" he said. \"I have a big project due in two days, and I have to get the demo for our group, 'Out of Batteries', finished. Can I use your wi-fi?\"",
      "\"The demo?\" Takumi crossed his arms. \"You were supposed to have that finished last week,\" he said. \"Quiet Signal Records wants it by tomorrow.\"",
      "\"Sorry about that.\" Daichi bowed. \"The project's been a nightmare.\"",
      "Takumi shook his head. \"Come in.\" He stood aside. \"What's in the bag?\"",
      "\"Just a little thanks,\" Daichi said. \"I know you like cream puffs. They had a cookie version in the store.\"",
      "\"I'll get you the wi-fi password.\" Takumi took the bag. Daichi followed him to the living room.",
      "\"Great. I'll get set up quickly and finish this project.\" Daichi put his computer on the table.",
      "\"Here's the wi-fi password.\" Takumi handed him a cup of coffee as well. \"When did your wi-fi go down?\"",
      "\"Last night,\" said Daichi. He took a sip of the coffee.",
      "\"Did you go to an internet cafe to work?\" Takumi asked.",
      "Daichi shook his head. \"No. My other project is very important. Then I have to upload some very important files. I couldn't trust their security,\" he said. \"I did as much work as I could offline until I figured it was okay to wake you up.\"",
      "\"Okay.\" Takumi stood up. \"Make yourself at home. I have to get ready for work.\"",
      "\"When do you leave?\" Daichi asked.",
      "\"I usually leave at eight, so I get up at seven,\" said Takumi.",
      "Daichi put his hands together in apology. \"Sorry. I didn't mean to wake you up so early.\"",
      "\"It's okay. I have more time to practice my keigo,\" Takumi said.",
      "\"Is that still giving you trouble?\" Daichi asked.",
      "\"Oh yeah.\" Takumi shook his head. \"I called my boss, 'Dude,' last week. He didn't mind, but the rest of the office laughed.\"",
      "Daichi laughed. \"That's why I love freelancing. Nobody to answer to.\"",
      "\"I'll let you work.\" Takumi went into the bathroom to get ready.",
      "When he came out twenty minutes later, Daichi was dusting his shelves with a cloth.",
      "\"What are you doing?\" asked Takumi.",
      "\"Your books were messy,\" said Daichi. \"And then I noticed that your shelves were very dusty.\" He shook his head. \"I couldn't work in a dirty room.\"",
      "Takumi took the cloth from Daichi. \"Your room is even dirtier,\" he said. \"You never clean it.\"",
      "\"I had to last night,\" said Daichi. He bit his lip. \"When the wi-fi went down, I couldn't sleep. I needed to clean.\"",
      "\"Later,\" said Takumi. \"Did you finish uploading the files?\"",
      "\"Yes, but I have to wait,\" said Daichi. \"The manager isn't in yet, and he needs to check them.\" He sat down on the floor.",
      "\"Why don't you work on the demo?\" asked Takumi.",
      "\"I will,\" said Daichi. \"Once the manager says my file is okay, I'll get started on the music demo. I can't focus on two things at once.\" He smiled. \"It should be ready soon.\"",
      "Takumi shook his head.",
      "\"I'm hungry,\" said Daichi. \"Do you want to go get some breakfast?\"",
      "\"I usually just have a banana for breakfast,\" said Takumi. \"I have some cereal if you want.\"",
      "Daichi yawned. \"Maybe later. Is it all right if I take a nap?\"",
      "\"That's right, you've been up all night.\" Takumi frowned. \"I have to leave in an hour.\"",
      "\"Okay,\" Daichi said. \"I'll go find an internet cafe.\"",
      "Takumi held out his hands. \"No. It's okay. You can stay here today,\" he said. \"I'll leave you my extra key. When you go outside, please lock the door.\"",
      "\"Thanks, buddy,\" Daichi said. \"I promise I won't make a mess.\"",
      "***SCENE_BREAK***",
      "\"So Daichi just turned up at your door this morning?\" asked Yui. She had bought three onigiri from the convenience store on the way to Takumi's apartment.",
      "\"Yes,\" said Takumi. \"He needed a place to finish a project. Then he would work on the demo. I let him use my wi-fi.\"",
      "\"You left Dai-chan all alone in your apartment,\" said Yui, smiling. \"Are you sure it was a good idea?\"",
      "\"Why?\" asked Takumi. \"He said he would finish the demo by this afternoon.\"",
      "Yui shook her head. \"I bet you these three onigiri that he hasn't,\" she said.",
      "\"You're on,\" Takumi said. He opened the door. The apartment was dark, but a loud snoring came from the front room.",
      "\"Daichi?\" Takumi and Yui went into the living room. Daichi was lying on the couch. His computer was dark.",
      "Takumi touched Daichi's shoulder. \"Hey. Are you okay?\"",
      "Daichi yawned. \"Takumi. You're home.\" He rubbed his eyes. \"Sorry. I fell asleep not long after you left. What time is it?\"",
      "\"Seven in the evening,\" said Takumi. \"I had some overtime. Are you hungry?\"",
      "\"Starving. Just let me check my email.\" Daichi turned on his computer.",
      "\"Still think he worked on the demo?\" whispered Yui.",
      "Takumi bit his lip.",
      "\"Great. My boss loved the project,\" Daichi said. \"I can get started on the demo right after dinner.\" He looked at Takumi. \"Where do you want to go? My treat.\"",
      "\"When will you start on the demo?\" asked Takumi.",
      "\"The minute we finish dinner.\" Daichi picked up his phone. \"I can't work on an empty stomach.\"",
      "Yui pulled Takumi away from the living room. \"Just so you know, I like salmon and kombu onigiri the best.\"",
      "***SCENE_BREAK***",
      "\"Are you sure you can't stay, Yui? You live near here. It would be no problem for you to get home.\" Daichi waved a slice of pizza in the air.",
      "\"Sorry, Dai-chan. I've got school in the morning, and Mom is coming home soon,\" Yui said. \"Besides, I want to watch that drama on U-Flicks. Tonight's the last night.\"",
      "\"Fine. Say hello to Nori-chan for me.\" Daichi took another bite of pizza.",
      "Yui waved goodbye at Takumi's door. At the door, she covered her smile. \"Good luck with Dai-chan.\"",
      "\"Thanks. I'll need it,\" Takumi said.",
      "Yui leaned in, whispering, \"You can get me the onigiri tomorrow.\"",
      "In the living room, Daichi was putting on some earphones. \"Oh, are you going to work on the demo?\"",
      "\"No. When Yui mentioned the video, I wanted to check it out,\" Daichi said. \"I'll get started on the demo after this.\"",
      "\"How much work do you have left on it, Daichi?\" Takumi asked.",
      "\"Maybe two or three hours,\" said Daichi. \"Everything is recorded. I just have to organize it.\"",
      "Takumi nodded. \"I'm going to take a shower. Do you want one?\"",
      "\"Yes. You don't mind?\" Daichi asked.",
      "\"No, it's okay,\" Takumi said.",
      "\"Great. I'll go after you.\" Daichi sat back and started watching a TV show.",
      "***SCENE_BREAK***",
      "\"I'll take a look at the demo now,\" Daichi said, drying his hair.",
      "Takumi looked at his watch. \"Do you need me for this? I have a meeting early tomorrow,\" he said.",
      "\"No, it's okay,\" said Daichi. \"I have a recording of our guitar work and Akira's drumming. I got lots of sleep today. Besides, I do my best work really late, anyway. Don't worry. I'll use my headphones.\"",
      "\"I'll trust you.\" Takumi went into his bedroom.",
      "***SCENE_BREAK***",
      "Blam!",
      "\"What the heck?\" Takumi jerked up in bed. It was four in the morning.",
      "Another loud bang came from the living room. Takumi yanked open his bedroom door.",
      "\"What's going on here?\" Takumi asked loudly.",
      "Daichi put down his controller. \"Sorry, buddy. I got too involved in the game.\"",
      "\"Game!\" Takumi said angrily. \"What about the demo?\"",
      "Daichi shook his head. \"No, I didn't like my voice, so I erased it,\" he said. \"I'll rerecord it tomorrow at my place. It's soundproof.\"",
      "\"Why do you have a soundproof room?\" Takumi asked.",
      "\"I had a YouTube channel where I uploaded games a few years ago,\" Daichi said. \"I don't use it much anymore, but I got five hundred thousand views. However, I was very noisy. The neighbors complained, so I made a soundproof room.\"",
      "Takumi closed Daichi's computer. \"What's this all about?\" he asked. \"Quiet Signal Records is giving us a chance. They are small, but this could be our break.\"",
      "\"I know, but...\" Daichi looked away.",
      "\"What is it?\" Takumi asked.",
      "\"My voice was terrible,\" Daichi said. \"Every time I listened to the recording, it sounded worse.\" He shuddered. \"I couldn't give them that.\"",
      "\"So, you waste time playing video games?\" said Takumi.",
      "\"I'm good at video games,\" said Daichi. \"Singing's difficult.\"",
      "\"It's not just me and you,\" Takumi said. \"Akira is counting on this. He wants to quit his teaching job.\"",
      "Daichi bit his lip. \"I know. I want to, but I can't. Something always distracts me. I've always been like this.\"",
      "Takumi shook his head. \"Come on. We're going back to your place,\" he said.",
      "\"Why?\" asked Daichi.",
      "\"It's soundproof, right?\" Takumi said.",
      "Daichi nodded.",
      "\"We're going to finish recording this demo tonight, even if it kills you,\" said Takumi.",
      "***SCENE_BREAK***",
      "\"There's the convenience store,\" said Daichi. \"Let's get a snack.\"",
      "\"No, you don't need a snack,\" said Takumi. \"Come on. Your apartment is only a few minutes away.\"",
      "Daichi kicked a rock. \"I work better with food,\" he said.",
      "\"I'll get you something when we finish,\" said Takumi.",
      "Daichi was silent the rest of the way to his building. At the elevator, he pushed the button for Kaoru's floor.",
      "\"What are you doing?\" Takumi asked.",
      "\"Kaoru might be up,\" said Daichi. \"She always has the best coffee in the morning.\"",
      "\"No. Let her sleep.\" Takumi pushed the button for Daichi's floor. He followed Daichi to his apartment.",
      "\"Wow! This is really clean,\" said Takumi.",
      "\"I know.\" Daichi rubbed the back of his neck. \"I hadn't realized how bad it was. I had three bags of garbage to take out,\" he said.",
      "\"Where's your soundproof room?\" asked Takumi.",
      "Daichi pointed to a small room in the back. Inside, there was a larger computer and a guitar on a rack.",
      "\"This is great,\" Takumi said. \"You made your YouTube channel here?\"",
      "Daichi nodded.",
      "\"I'll have to check it out,\" said Takumi. \"What game was it?\"",
      "\"An old horror game. It wasn't very good. You wouldn't be interested,\" said Daichi.",
      "\"No, I want to see it after,\" said Takumi, picking up the guitar. \"I'll play while you record your voice.\"",
      "\"Yes, that's great,\" said Daichi softly. \"Do you need a drink before we start? I don't have any coffee left. I'll go to the store and get some. There's a twenty-four-hour supermarket near here.\" He stood up.",
      "Takumi sighed. \"What's wrong, Daichi?\" Takumi asked. \"You don't want to record this demo, do you?\"",
      "\"I do!\" Daichi crossed his arms.",
      "\"Then what is it? Why are you acting so strangely?\" Takumi asked.",
      "Daichi flopped into his computer chair. \"I love making music. I want to make the demo, but what if the music people hate it?\"",
      "\"Then we try again,\" said Takumi. \"If they say no, it isn't the end of the world. I'm sure you made many mistakes when playing your games.\"",
      "Daichi bit his lip. \"Yeah. Many mistakes,\" he said softly.",
      "\"What happened?\" Takumi asked.",
      "Daichi was silent. He took a deep breath. \"Gaming was easy. My channel was growing. I was even adding new games all the time.\" He smiled. \"I stopped sleeping. Yui was so worried about me and got Kaoru to make sure I slept. We went to the same high school. After graduating, we continued to hang out.\"",
      "\"Ka-chan?\" Takumi raised an eyebrow.",
      "Daichi smiled. \"Yeah. Yui started calling her Ka-chan then. It was fine, but I got too big and too successful,\" he said. \"I made some mistakes. After that, the negative comments started pouring in.\"",
      "\"What kind?\" asked Takumi.",
      "\"Stories that I was using Chappy to play the games,\" said Daichi. \"There were others. They were worse. They weren't true, but then the comments got scary.\"",
      "\"How scary?\" asked Takumi.",
      "\"I almost went to the police,\" said Daichi, looking away. \"You remember how I was when we first met?\"",
      "\"You were pretty quiet. A far cry from now.\" Takumi waited for Daichi to continue.",
      "\"Yeah. I stopped playing games, shut down my channel. Then I stayed in my apartment for a year,\" said Daichi.",
      "\"A year?\" Takumi raised an eyebrow. \"I can't see it.\"",
      "Daichi smiled. \"Kaoru and Yui would come over sometimes. One day, they pulled me out to join an English circle. I'd done a three-month homestay in Australia a few years ago. They thought it might help.\"",
      "\"That's where we met,\" said Takumi. \"You were pretty quiet the first few times. But your English was much better than Yui's.\"",
      "Daichi nodded. \"I wasn't sure I could still speak English, but your conversation was pretty easy,\" he said. \"And your Japanese is much better, minus the keigo.\"",
      "\"I'm trying.\" Takumi frowned.",
      "\"I know,\" said Daichi. \"I'm not worried about singing for a small audience. That's fun. But what if I make a mistake and Quiet Signal Records hate me?\"",
      "Takumi took a deep breath. \"I see.\" He picked up the mic. \"Your songs are great. I know them well, so I'll sing. You're okay with the guitar. Make sure you get a good recording.\"",
      "\"But I'm a better singer,\" said Daichi.",
      "\"That's right, you are,\" said Takumi. \"But I have a thicker skin. For me, mistakes are okay. I don't mind it when people criticize me, if I can improve. But if they are too strong, I ignore them, after punching the person who said it.\" He smiled.",
      "Daichi stepped back. \"Do you really punch them?\"",
      "\"No. I just imagine it.\" Takumi chuckled. \"Besides, I'm much better looking. I always thought I would make a much better leader.\"",
      "Daichi grabbed the mic. \"I wrote this song,\" he said.",
      "\"Yes, and it needs a handsome boy to sing it.\" Takumi sighed. \"Good thing I'm here.\"",
      "\"Those are fighting words,\" Daichi grunted.",
      "\"Are you going to sing?\" Takumi asked.",
      "\"Yes, but not with you here,\" Daichi said. \"Go downstairs to Kaoru's place and get me some coffee. She has the best blend. I'll finish the song. We'll check it out when you come back.\"",
      "***SCENE_BREAK***",
      "I hope she hasn't done her makeup yet. Takumi knocked on the door to Kaoru's place. He heard a shuffling behind it. Kaoru's messy head popped out.",
      "\"It's six o'clock in the morning,\" yawned Kaoru. \"Why are you here so early?\"",
      "\"Goodnight Kitty slippers? Where are the pajamas?\" Takumi smiled. The messy hair was off-limits.",
      "\"I will punch you.\" Kaoru smacked her fist into her hand. \"Why are you here?\"",
      "\"Daichi is recording our demo,\" said Takumi. \"He wanted some coffee.\"",
      "\"I see. Come in.\" Kaoru smoothed her hair. \"Just wait in the entrance. I'll bring you the coffee.\" She went back to the kitchen.",
      "\"Is your wi-fi still down?\" Takumi followed her.",
      "\"What do you mean?\" Kaoru set the drip coffee pot on the counter. \"Why didn't you wait in the entrance?\"",
      "\"It's cold there.\" Takumi shrugged. \"Daichi said the wi-fi in the building was down. He came to my place yesterday to work on his project.\" Takumi sat down at her table.",
      "\"Oh. That was repaired yesterday afternoon.\" Kaoru poured some hot water into the drip pot.",
      "\"Why was it down?\" asked Takumi.",
      "Kaoru brought Takumi two mugs of coffee. She set them on the table, then went back for a third. \"Daichi didn't tell you?\"",
      "Takumi shook his head.",
      "\"I don't know how he did it, but Daichi knocked out the wi-fi for the whole building,\" said Kaoru. \"He said it was an accident.\"",
      "\"Really?\" said Takumi. \"Maybe he was streaming a game again, and something happened.\"",
      "Kaoru stepped back. \"He told you about that?\"",
      "Takumi nodded.",
      "\"Wow.\" Kaoru tucked a lock of hair behind her ear.",
      "\"Daichi said he got some negative reviews,\" said Takumi.",
      "\"Yes. That's putting it mildly,\" Kaoru said.",
      "\"Really? He didn't tell me they were that bad,\" Takumi said.",
      "\"He didn't?\" Kaoru took a sip of coffee.",
      "Takumi shook his head.",
      "Kaoru crossed her arms. \"They were pretty personal.\"",
      "\"That's okay,\" said Takumi. \"I don't want to know all the details. Daichi will tell me when he's ready.\" He picked up the coffee mugs.",
      "\"You know, I'm glad you became his friend, Takumi,\" Kaoru said.",
      "\"Me too,\" Takumi said. \"I'll bring the mugs back later.\"",
      "\"Don't worry about it,\" Kaoru said. \"I got them at the Hundred-Yen Store. Daichi already has twenty of them.\"",
      "***SCENE_BREAK***",
      "Daichi's apartment was quiet when Takumi went inside. His stomach fell. Is he cleaning again?",
      "Daichi opened the door to his studio. \"I'm finished. Where's my coffee?\"",
      "Takumi handed him the mug. \"I just got back.\" He took a sip. \"Do you want me to stay here until you send it?\"",
      "\"No, I should be okay,\" Daichi said. \"But if you could listen to the recording before you leave, that would be great.\"",
      "\"The wi-fi is working?\" Takumi asked.",
      "\"Yeah. It looks like they fixed it last night,\" said Daichi.",
      "\"That's what Kaoru said.\" Takumi looked over his mug.",
      "Daichi swallowed his coffee quickly, coughing. \"Did she say anything else?\"",
      "\"She said you knocked it out,\" said Takumi.",
      "Daichi looked at his door. \"It was an accident. I swear. I was trying to make it go faster.\"",
      "\"I believe you,\" said Takumi. \"Play the song. I have to go to work.\" He followed Daichi into the studio.",
      "Daichi put on the music. Takumi's guitar and Akira's drums for 'Lost in the Night' filled the room. \"This part is good,\" said Daichi.",
      "\"Be quiet,\" said Takumi. He took another sip of his coffee.",
      "Daichi's voice started slowly. He sang about meeting someone on a train platform late at night, but not seeing their face.",
      "\"I always wondered where you got the idea for this song,\" Takumi said.",
      "\"Quiet. We're getting to the good part,\" said Daichi.",
      "The song finished with Daichi watching the person disappear from the platform. He turned off the tape.",
      "\"It's really good. Much better than the live version,\" said Takumi. \"A little sad for a demo.\"",
      "\"I know. I have the pop song you sang as well,\" said Daichi. \"I'll include it.\"",
      "\"Great,\" said Takumi. \"Quiet Signal Records will love it,\" he said.",
      "\"I hope so,\" said Daichi.",
      "Takumi drank the rest of his coffee. \"I'll stop by after work to check on you,\" he said.",
      "\"Don't worry. It's ready. I'll send the demo before lunch,\" said Daichi.",
      "\"I know. I trust you,\" said Takumi. \"Then we can celebrate with some sushi. I'll call Yui and Kaoru. I need to get Yui some onigiri.\"",
      "\"Sounds great,\" said Daichi.",
      "Takumi put his coffee cup down. \"Don't forget to bring back the coffee cups.\" He held up a closed fist.",
      "Daichi met it. He looked at his cupboard. \"I do have a lot.\"",
      "\"See you tonight,\" said Takumi.",
      "\"Takumi...\" Daichi bit his lip.",
      "\"Don't worry about it, buddy. You can tell me more when you're ready,\" Takumi said. \"Until then, I'm still the better choice to be the leader.\"",
      "Daichi shook his head. \"Over my dead body.\"",
      "Takumi gave him another fist bump as he left Daichi's apartment.",
      "Finishing his coffee, Daichi went back to his computer. He opened up his e-mail. The message to Quiet Signal Records flashed on the screen. \"It'll be okay.\" He clicked on send."
  ],
  "vocabulary": [
      { "word": "dark circles", "translation": "\u76ee\u306e\u4e0b\u306e\u30af\u30de", "partOfSpeech": "noun phrase", "example": "He looked exhausted. There were dark circles under his eyes." },
      { "word": "offline", "translation": "\u30aa\u30d5\u30e9\u30a4\u30f3\uff08\u3067\uff09", "partOfSpeech": "adjective/adverb", "example": "I did as much work as I could offline." },
      { "word": "freelancing", "translation": "\u30d5\u30ea\u30fc\u30e9\u30f3\u30b9\u3067\u50cd\u304f\u3053\u3068", "partOfSpeech": "verb (-ing form)", "example": "That's why I love freelancing." },
      { "word": "soundproof", "translation": "\u9632\u97f3\u306e", "partOfSpeech": "adjective", "example": "I'll rerecord it tomorrow at my place. It's soundproof." },
      { "word": "blend", "translation": "\u30d6\u30ec\u30f3\u30c9\uff08\u30b3\u30fc\u30d2\u30fc\u306e\u7a2e\u985e\uff09", "partOfSpeech": "noun", "example": "She has the best blend." },
      { "word": "rejection", "translation": "\u4e0d\u63a1\u7528\u30fb\u62d2\u5426", "partOfSpeech": "noun", "example": "One rejection isn't the end of the world." },
      { "word": "criticize", "translation": "\u6279\u5224\u3059\u308b \u203b\u30af\u30ec\u30fc\u30e0\u306f\u82f1\u8a9e\u3067\u300cclaim\uff08\u4e3b\u5f35\u3059\u308b\uff09\u300d\u306e\u610f\u5473", "partOfSpeech": "verb", "example": "I don't mind it when people criticize me." },
      { "word": "controller", "translation": "\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u30fc", "partOfSpeech": "noun", "example": "Daichi put down his controller." }
  ],
  "idioms": [
      { "phrase": "make yourself at home", "meaning": "relax and act as if you are in your own home", "translation": "\u304f\u3064\u308d\u3044\u3067\u304f\u3060\u3055\u3044", "example": "Make yourself at home. I have to get ready for work." },
      { "phrase": "you're on", "meaning": "I accept your bet", "translation": "\u4e57\u3063\u305f\uff01\uff08\u8ce2\u3051\u306b\u540c\u610f\u3059\u308b\uff09", "example": "I bet you these three onigiri that he hasn't. \u2014 You're on." },
      { "phrase": "my treat", "meaning": "I will pay for this", "translation": "\u79c1\u306e\u304a\u3054\u308a\u3067\u3059", "example": "Where do you want to go? My treat." },
      { "phrase": "thicker skin", "meaning": "the ability to receive criticism without feeling upset", "translation": "\u6279\u5224\u306b\u5f37\u3044\u30fb\u6253\u305f\u308c\u5f37\u3044", "example": "I have a thicker skin. For me, mistakes are okay." },
      { "phrase": "not the end of the world", "meaning": "not as bad as it seems; things will be okay", "translation": "\u4e16\u754c\u306e\u7d42\u308f\u308a\u3067\u306f\u306a\u3044\uff08\u5927\u3057\u305f\u3053\u3068\u3067\u306f\u306a\u3044\uff09", "example": "One rejection isn't the end of the world." },
      { "phrase": "pouring in", "meaning": "arriving in large amounts, often quickly (used for messages, comments, or emotions)", "translation": "\u5927\u91cf\u306b\u62bc\u3057\u5bc4\u305b\u308b\u30fb\u6bba\u5230\u3059\u308b", "example": "The negative comments started pouring in." },
      { "phrase": "get started on", "meaning": "to begin working on something", "translation": "\u301c\u306b\u53d6\u308a\u304b\u304b\u308b", "example": "I can get started on the demo right after dinner." },
      { "phrase": "check it out", "meaning": "to look at or listen to something (informal)", "translation": "\u30c1\u30a7\u30c3\u30af\u3059\u308b\u30fb\u898b\u3066\u307f\u308b", "example": "I'll have to check it out." },
      { "phrase": "turn up", "meaning": "to arrive, often without planning (informal)", "translation": "\u3072\u3087\u3063\u3053\u308a\u73fe\u308c\u308b", "example": "So Daichi just turned up at your door this morning?" },
      { "phrase": "pull someone out", "meaning": "to help someone leave a difficult situation", "translation": "\uff08\u56f0\u96e3\u306a\u72b6\u6cc1\u304b\u3089\uff09\u5f15\u304d\u51fa\u3059", "example": "One day, they pulled me out to join an English circle." },
      { "phrase": "over my dead body", "meaning": "I will never allow this to happen (very strong refusal, often used humorously)", "translation": "\u7d76\u5bfe\u306b\u30c0\u30e1\u3060\uff08\u5f37\u3044\u62d2\u5426\u3002\u30e6\u30fc\u30e2\u30a2\u3067\u4f7f\u3046\u3053\u3068\u3082\u591a\u3044\uff09", "example": "I'm still the better choice to be the leader. \u2014 Over my dead body." },
      { "phrase": "hold your horses", "meaning": "wait a moment; don't be in such a hurry", "translation": "\u3061\u3087\u3063\u3068\u5f85\u3063\u3066\u30fb\u6162\u3066\u306a\u3044\u3067", "example": "Hold your horses, I'm coming!" },
      { "phrase": "knocked out", "meaning": "caused something (like power or internet) to stop working", "translation": "\uff08\u96fb\u6c17\u3084\u30cd\u30c3\u30c8\u306a\u3069\u3092\uff09\u6b62\u3081\u3066\u3057\u307e\u3046\u30fb\u6545\u969c\u3055\u305b\u308b", "example": "Daichi knocked out the wi-fi for the whole building." },
      { "phrase": "a far cry from", "meaning": "very different from", "translation": "\u301c\u3068\u306f\u304b\u3051\u96e2\u308c\u3066\u3044\u308b\u30fb\u5927\u9055\u3044", "example": "You were pretty quiet. A far cry from now." },
      { "phrase": "off-limits", "meaning": "not allowed to be touched, mentioned, or gone near", "translation": "\u7acb\u3061\u5165\u308a\u7981\u6b62\u30fb\u89e6\u308c\u3066\u306f\u3044\u3051\u306a\u3044", "example": "The messy hair was off-limits." },
      { "phrase": "fighting words", "meaning": "words that will likely start an argument or fight (often used jokingly)", "translation": "\u3051\u3093\u304b\u3092\u58f2\u308b\u3088\u3046\u306a\u8a00\u8449\uff08\u5192\u8ac7\u3067\u4f7f\u3046\u3053\u3068\u3082\u591a\u3044\uff09", "example": "Those are fighting words." },
      { "phrase": "putting it mildly", "meaning": "describing something in a softer way than it really is; understating", "translation": "\u63a7\u3048\u3081\u306b\u8a00\u3063\u3066\u3082\u305d\u3093\u306a\u3082\u306e\u3067\u306f\u306a\u3044", "example": "Yes. That's putting it mildly." },
      { "phrase": "even if it kills you", "meaning": "no matter how difficult or unpleasant it is (used for emphasis, often humorously)", "translation": "\u305f\u3068\u3048\u6b7b\u306c\u307b\u3069\u5927\u5909\u3067\u3082\uff08\u5f37\u8abf\u30fb\u5192\u8ac7\u4ea4\u3058\u308a\u306b\u4f7f\u3046\uff09", "example": "We're going to finish recording this demo tonight, even if it kills you." }
  ],
  "workbook": {
      "wordBank": [
          "dark circles",
          "offline",
          "freelancing",
          "soundproof",
          "blend",
          "rejection",
          "criticize",
          "controller",
          "pouring in",
          "get started on",
          "check out",
          "pulled out",
          "turned up",
          "hold your horses",
          "knocked out",
          "a far cry from",
          "off-limits",
          "fighting words",
          "putting it mildly",
          "even if it kills you"
      ],
      "fillInBlank": [
          "Daichi had ______ under his eyes because he had been up all night.",
          "Daichi did as much work as he could ______ before uploading the files.",
          "Daichi loves ______ because he can work whenever he wants.",
          "Daichi's studio is ______, so his neighbors can't hear him sing.",
          "Kaoru always has the best coffee ______ in the morning.",
          "Takumi told Daichi that one ______ isn't the end of the world.",
          "Takumi said he doesn't mind when people ______ him.",
          "Daichi put down his ______ when Takumi walked in.",
          "Daichi's YouTube channel was growing fast. Then the negative comments started ______.",
          "Takumi said, \"I have to leave soon, but let's ______ the demo first.\"",
          "\"There's a great new song on the radio,\" said Yui. \"You should ______ that song.\"",
          "Kaoru and Yui ______ Daichi from his apartment after he stayed inside for a year.",
          "Nobody invited Daichi. He just ______ at Takumi's door at six in the morning.",
          "\"You should ______ Daichi's old YouTube channel,\" said Takumi. \"It was very popular.\"",
          "\"______, I'm coming!\" Takumi yawned, yanking open the door.",
          "\"I don't know how he did it, but Daichi ______ the wi-fi for the whole building,\" said Kaoru.",
          "\"You were pretty quiet. ______ now,\" said Takumi.",
          "The messy hair was ______.",
          "\"Those are ______,\" Daichi grunted.",
          "\"Yes. That's ______,\" Kaoru said.",
          "\"We're going to finish recording this demo tonight, ______,\" said Takumi."
      ],
      "fillInBlankAnswers": [
          "dark circles",
          "offline",
          "freelancing",
          "soundproof",
          "blend",
          "rejection",
          "criticize",
          "controller",
          "pouring in",
          "get started on",
          "check out",
          "pulled out",
          "turned up",
          "check out",
          "hold your horses",
          "knocked out",
          "a far cry from",
          "off-limits",
          "fighting words",
          "putting it mildly",
          "even if it kills you"
      ],
      "multipleChoice": [
          {
              "question": "What does \"make yourself at home\" mean?",
              "options": [
                  "Relax and act as if you are in your own home.",
                  "I will pay for this.",
                  "I accept your bet."
              ],
              "answer": 0,
              "explanation": "It's used to tell a guest to relax, not to talk about paying or betting."
          },
          {
              "question": "What does \"you're on\" mean?",
              "options": [
                  "I will pay for this.",
                  "I accept your bet.",
                  "Not as bad as it seems; things will be okay."
              ],
              "answer": 1,
              "explanation": "\"You're on\" is used to accept a bet or challenge."
          },
          {
              "question": "What does \"my treat\" mean?",
              "options": [
                  "I will pay for this.",
                  "The ability to receive criticism without feeling upset.",
                  "I will never allow this (strong refusal)."
              ],
              "answer": 0,
              "explanation": "\"My treat\" means the speaker is paying for something."
          },
          {
              "question": "What does \"not the end of the world\" mean?",
              "options": [
                  "I accept your bet.",
                  "Not as bad as it seems; things will be okay.",
                  "Relax and act as if you are in your own home."
              ],
              "answer": 1,
              "explanation": "It's used to reassure someone that a bad result isn't a disaster."
          },
          {
              "question": "What does \"over my dead body\" mean?",
              "options": [
                  "I will never allow this to happen (a strong, often humorous refusal).",
                  "I will pay for this.",
                  "The ability to receive criticism without feeling upset."
              ],
              "answer": 0,
              "explanation": "It's a strong (often joking) way of refusing to let something happen."
          },
          {
              "question": "What does \"thicker skin\" mean?",
              "options": [
                  "Not as bad as it seems; things will be okay.",
                  "The ability to receive criticism without feeling upset.",
                  "I accept your bet."
              ],
              "answer": 1,
              "explanation": "Having a \"thicker skin\" means criticism doesn't bother you much."
          }
      ],
      "writeYourOwn": [
          {
              "phrase": "off-limits",
              "meaning": "Not allowed to be touched, mentioned, or gone near. Example: \"The messy hair was off-limits.\"",
              "prompt": "Write a sentence using \"off-limits.\" Think of a topic or thing you consider off-limits."
          },
          {
              "phrase": "a far cry from",
              "meaning": "Very different from. Example: \"You were pretty quiet. A far cry from now.\"",
              "prompt": "Write a sentence using \"a far cry from.\" Compare how something is now to how it used to be."
          },
          {
              "phrase": "putting it mildly",
              "meaning": "Describing something in a softer way than it really is. Example: \"Yes. That's putting it mildly.\"",
              "prompt": "Write a sentence using \"putting it mildly.\" Think of a time an understatement made something funny or dramatic."
          }
      ]
  }
};

export default bookContent;
